{{- if .Values.api.ingress.enabled -}}
{{- $fullName := include "kubeUp.apiName" . -}}
{{- $svcPort := .Values.api.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "kubeUp.apiName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeUp.apiLabels" . | nindent 4 }}
{{- if .Values.api.ingress.annotations }}
  annotations:
{{- with .Values.api.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  {{- if .Values.api.ingress.className }}
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- end }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- range .Values.api.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.api.ingress.path }}
            pathType: {{ $.Values.api.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
{{- end }}
