apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeUp.managerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeUp.managerLabels" . | nindent 4 }}
{{- if .Values.manager.serviceAccount.annotations -}}
  annotations:
{{- with .Values.manager.serviceAccount.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
