apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeUp.apiName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeUp.apiLabels" . | nindent 4 }}
{{- if .Values.api.serviceAccount.annotations -}}
  annotations:
{{- with .Values.api.serviceAccount.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
