apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeUp.managerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeUp.managerLabels" . | nindent 4 }}
  annotations:
{{- with .Values.manager.service.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - name: {{ template "portNames.metrics" . }}
      port: {{ .Values.manager.service.metricsPort }}
      protocol: {{ .Values.manager.deployment.protocol }}
      targetPort: {{ template "portNames.metrics" . }}
    - name: {{ template "portNames.health" . }}
      port: {{ .Values.manager.service.healthPort }}
      protocol: {{ .Values.manager.deployment.protocol }}
      targetPort: {{ template "portNames.health" . }}
  selector:
    {{- include "kubeUp.managerSelectorLabels" . | nindent 4 }}
